-- The official postgres image bootstraps POSTGRES_USER via initdb, which
-- ALWAYS makes that role a superuser (Postgres requires a superuser bootstrap
-- role for initdb to run at all). Superusers bypass Row-Level Security
-- unconditionally, even on tables with FORCE ROW LEVEL SECURITY — so left
-- alone, every RLS policy in migration 0002 would be silently inert for the
-- app's own connection.
--
-- This runs once, automatically, on first cluster initialization only
-- (docker-entrypoint-initdb.d scripts do not re-run against an existing,
-- already-initialized data volume). If you already have a postgres_data
-- volume from before this file existed, run this statement manually once
-- against it instead: `ALTER ROLE deliverypilot NOSUPERUSER;`
ALTER ROLE deliverypilot NOSUPERUSER;
